### ISSUE TITLE
mailbox metrics are not flushed into ES

### ISSUE THREAD

**Issue by alonsnir** [markkimsal/statsd-elasticsearch-backend#12]
Hi,

i'm collecting akka metrics with Kamon, send it to StatsD and from there into ES
but some metrics are omitted.
what could be wrong?
OK:
{"count_90":"23","mean_90":"45796.17391304348","upper_90":"235520","sum_90":"1053312","sum_squares_90":"90439655424","std":"86686.17211804891","upper":"385024","lower":"11264","count":"25","count_ps":"2.5","sum":"1690240","sum_squares":"302138761216","mean"
:"67609.6","median":"44032","@timestamp":"1424358610000","ns":"kamon","grp":"is-performance-srv","tgt":"actor","act":"user_dataSetService_c"}

flushed 97 stats to ES

NOT OK:
19 Feb 15:10:20 - DEBUG: kamon.is-performance-srv.router.user_healthCheckService.errors:0|c
{"counters":{"statsd.bad_lines_seen":0,"statsd.packets_received":61,"statsd.metrics_received":670,"kamon.is-performance-srv.actor.user_etlService_a.errors":0,"kamon.is-performance-srv.actor.user_statsd-metrics-sender.errors":0,"kamon.is-performance-srv.acto
r.user_schemaService.errors":0,"kamon.is-performance-srv.router.user_schemaService.errors":0,"kamon.is-performance-srv.actor.user_dataSetService_b.errors":0,"kamon.is-performance-srv.actor.user_a.errors":0,"kamon.is-performance-srv.actor.user_dataCollection
Service.errors":0,"kamon.is-performance-srv.router.user_dataCollectionService.errors":0,"kamon.is-performance-srv.actor.user_dataSetService_a.errors":0,"kamon.is-performance-srv.actor.user_schemaService_c.errors":0,"kamon.is-performance-srv.actor.user_dataC
ollectionService_a.errors":0,"kamon.is-performance-srv.actor.system.errors":0,"kamon.is-performance-srv.actor.user_etlService.errors":0,"kamon.is-performance-srv.router.user_etlService.errors":0,"kamon.is-performance-srv.actor.user_dataCollectionService_b.e
rrors":0,"kamon.is-performance-srv.actor.user_kamon-metrics-subscriptions.errors":0,"kamon.is-performance-srv.actor.user_healthCheckService_b.errors":0,"kamon.is-performance-srv.actor.user_dataSetService_c.errors":0,"kamon.is-performance-srv.actor.user.erro
rs":0,"kamon.is-performance-srv.actor.user_schemaService_a.errors":0,"kamon.is-performance-srv.actor.user_etlService_c.errors":0,"kamon.is-performance-srv.actor.user_dataCollectionService_c.errors":0,"kamon.is-performance-srv.actor.user_etlService_b.errors"
:0,"kamon.is-performance-srv.actor.user_dataSetService.errors":0,"kamon.is-performance-srv.router.user_dataSetService.errors":0,"kamon.is-performance-srv.actor.user_healthCheckService_c.errors":0,"kamon.is-performance-srv.actor.user_schemaService_b.errors":
0,"kamon.is-performance-srv.actor.user_healthCheckService_a.errors":0,"kamon.is-performance-srv.actor.user_healthCheckService.errors":0,"kamon.is-performance-srv.router.user_healthCheckService.errors":0},"gauges":{"statsd.timestamp_lag":1},"timers":{"kamon.
is-performance-srv.actor.user_etlService_a.mailbox-size":[0,0,0,0,0,0,0,0,0,0],"kamon.is-performance-srv.actor.user_statsd-metrics-sender.processing-time":[917504,929792,987136,987136,999424,1040384,1122304,1228800,1548288,1802240],"kamon.is-performance-srv
.actor.user_statsd-metrics-sender.mailbox-size":[0,0,0,0,0,0,0,0,0,0,1],"kamon.is-performance-srv.actor.user_statsd-metrics-sender.time-in-mailbox":[13120,13440,13760,13888,14400,14464,14656,19840,20736,22272],"kamon.is-performance-srv.actor.user_schemaServ
ice.mailbox-size":[0,0,0,0,0,0,0,0,0,0],"kamon.is-performance-srv.actor.user_dataSetService_b.mailbox-size":[0,0,0,0,0,0,0,0,0,0,1,1],

**Comment by megastef** [comment]
Do you have a mapping for Elasticsearch in place?

**Comment by alonsnir** [comment]
I missed that part at the beginning, but then once figured out, run the
es-index-template.sh. So yes, mapping is in place, values arrive into
elastic typed.

**Comment by markkimsal** [comment]
Is this closed then?

Is there anyway to make this work that doesn't require the mapping?  Should the mapping file be renamed at all to make it more obvious?  Lots of people have some issues related to not installing the mapping.

**Comment by alonsnir** [comment]
Not closed.

I just answered that mappings are in place and some metrics got into ES
properly, but not actor's mailbox metrics.

**Comment by markkimsal** [comment]
Can you pull the latest commit and add 'debug: true' to the top level configuration object?  This should more clearly print the metrics object and what is sent to ES.

**Comment by markkimsal** [comment]
Are the missing metrics all of the type 'gauge'?

**Comment by alonsnir** [comment]
can't tell about the type. i think it's a histogram. here is a sample of
missing metric
"kamon.is-performance-srv
.actor.user_statsd-metrics-sender.mailbox-size":[0,0,0,0,0,0,0,0,0,0,1]

i have moved to Graphite/Grafana, so for me this became not an issue.

thanks for support

**Comment by uschen** [comment]
@markkimsal all `gauges` are ignored?

**Comment by markkimsal** [comment]
@uschen yes guages are not implemented yet.

**Comment by markkimsal** [comment]
I added support for gauges.

**Comment by uschen** [comment]
@markkimsal awesome!
