### ISSUE TITLE
timing packet elasticsearch indexing

### ISSUE THREAD

**Issue by peterbale** [markkimsal/statsd-elasticsearch-backend#17]
I am having trouble getting my statsd timing packets displaying in kibana correctly. All other types of packets are mapped as they should (using @ysubach TIMESTAMP fix), however, when I send timing packets kibana throws various mapping errors. My kibana field is showing the following:

upper  	conflict 	true	false	
5
sum  	conflict 	true	false	
1
upper_90  	conflict 	true	false	
0
count_90  	conflict 	true	false	
0
sum_squares  	conflict 	true	false	
0
sum_squares_90  	conflict 	true	false	
0
count_ps  	conflict 	true	false	
1
std  	conflict 	true	false	
0
bin_inf  	number	false	true	
0
lower  	conflict 	true	false	
0
count  	conflict 	true	false	
4
sum_90  	conflict 	true	false	
1
bin_100  	number	false	true	
0
bin_500  	number	false	true	
0
median  	conflict 	true	false	
0

Is there something I can change within the elasticsearch.js file? I think the problem is I am setting the dafault mapping using the sh node_modules/statsd-elasticsearch-backend/es-index-template.sh, however, statsd is still sending various fields as strings.

**Comment by markkimsal** [comment]
The TIMESTAMP "fix" you mention is not the correct way to send data to ES.  Statsd does not "send data as a string", the mapping you define for ES interprets the incoming ASCII data in a way that you specify.

Can you attach the following things:
  The ES type that has the problem
  The ES mapping for that type
  A debug CLI capture that is sending data that isn't saved correctly?

**Comment by peterbale** [comment]
This is the debug statsd output:

17 Apr 10:44:14 - DEBUG: ES payload:
17 Apr 10:44:14 - DEBUG: {"index":{"_index":"statsd-2015.04.17","_type":"counter"}}
{"ns":"statsd","grp":"bad_lines_seen","tgt":"","act":"","val":"0","@timestamp":"1429263855000"}
{"index":{"_index":"statsd-2015.04.17","_type":"counter"}}
{"ns":"statsd","grp":"packets_received","tgt":"","act":"","val":"7","@timestamp":"1429263855000"}
{"index":{"_index":"statsd-2015.04.17","_type":"counter"}}
{"ns":"statsd","grp":"metrics_received","tgt":"","act":"","val":"7","@timestamp":"1429263855000"}
{"index":{"_index":"statsd-2015.04.17","_type":"timer"}}
{"ns":"this","grp":"is","tgt":"a","act":"test","val":"452","@timestamp":"1429263855000"}
{"index":{"_index":"statsd-2015.04.17","_type":"timer"}}
{"ns":"this","grp":"is","tgt":"a","act":"test","val":"452","@timestamp":"1429263855000"}
{"index":{"_index":"statsd-2015.04.17","_type":"timer"}}
{"ns":"this","grp":"is","tgt":"a","act":"test","val":"452","@timestamp":"1429263855000"}
{"index":{"_index":"statsd-2015.04.17","_type":"timer"}}
{"ns":"this","grp":"is","tgt":"a","act":"test","val":"452","@timestamp":"1429263855000"}
{"index":{"_index":"statsd-2015.04.17","_type":"timer"}}
{"ns":"this","grp":"is","tgt":"a","act":"test","val":"452","@timestamp":"1429263855000"}
{"index":{"_index":"statsd-2015.04.17","_type":"timer"}}
{"ns":"this","grp":"is","tgt":"a","act":"test","val":"452","@timestamp":"1429263855000"}
{"index":{"_index":"statsd-2015.04.17","_type":"timer"}}
{"ns":"this","grp":"is","tgt":"a","act":"test","val":"452","@timestamp":"1429263855000"}
{"index":{"_index":"statsd-2015.04.17","_type":"timer_data"}}
{"count_90":"6","mean_90":"452","upper_90":"452","sum_90":"2712","sum_squares_90":"1225824","std":"0","upper":"452","lower":"452","count":"7","count_ps":"0.7","sum":"3164","sum_squares":"1430128","mean":"452","median":"452","@timestamp":"1429263855000","ns":"this","grp":"is","tgt":"a","act":"test"}

My ES mapping is:

{"statsd-2015.04.17":{"mappings":{"timer":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"act":{"type":"string","index":"not_analyzed"},"grp":{"type":"string","index":"not_analyzed"},"ns":{"type":"string","index":"not_analyzed"},"tgt":{"type":"string","index":"not_analyzed"},"val":{"type":"long"}}},"counter":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"act":{"type":"string","index":"not_analyzed"},"grp":{"type":"string","index":"not_analyzed"},"ns":{"type":"string","index":"not_analyzed"},"tgt":{"type":"string","index":"not_analyzed"},"val":{"type":"long"}}},"timer_data":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"act":{"type":"string","index":"not_analyzed"},"bin_100":{"type":"integer"},"bin_1000":{"type":"integer"},"bin_500":{"type":"integer"},"bin_inf":{"type":"integer"},"count":{"type":"float"},"count_90":{"type":"string"},"count_ps":{"type":"float"},"grp":{"type":"string","index":"not_analyzed"},"lower":{"type":"float"},"mean":{"type":"float"},"mean_90":{"type":"float"},"median":{"type":"float"},"ns":{"type":"string","index":"not_analyzed"},"std":{"type":"float"},"sum":{"type":"float"},"sum_90":{"type":"float"},"sum_squares":{"type":"string"},"sum_squares_90":{"type":"string"},"tgt":{"type":"string","index":"not_analyzed"},"upper":{"type":"float"},"upper_90":{"type":"float"}}}}}}

I send a timer_data UDP packet (this.is.a.test:452|ms) to statsd and the mapping errors I receive are: upper, sum, upper_90, count_90, sum_squares, sum_squares_90, count_ps, std, lower, count, sum_90 and median.

**Comment by markkimsal** [comment]
I just tried everything from a fresh install and I don't see any errors.  What is the real problem you're having with kibana?

**Comment by peterbale** [comment]
The problem I am having is the error with mapping within kibana when I use specific statsd packets (kibana 4, es v 1.5.1). It could be due to changing the elasticsearch.js file which is disrupting the mapping. I will restart on a clean node and see if that works. Can you confirm that sending timer packets (e.g. this.is.a.test:452|ms) are properly displayed in kibana, assuming you run the sh node_modules/statsd-elasticsearch-backend/es-index-template.sh script prior to starting statsd? Thanks.

**Comment by peterbale** [comment]
It has worked at last! I have been going around in circles with this problem and must have overwritten es indexes multiple times. The setup now is brilliant, this plugin makes my ELK stack so much more powerful, thanks!
