### ISSUE TITLE
ElasticSearch 2.0 support

### ISSUE THREAD

**Issue by imreACTmd** [markkimsal/statsd-elasticsearch-backend#21]
ES2.0 fails on entries because the date format handling has changed. If the date format is defined as dateOptionalTime, then ES2.0 will reject epoch timestamps that have millisecond resolutions.

Removing the specified date format allows the reasonable default date formatter to work and accept epoch_millis timestamps in ES2.0 and also on ES1.7

I sent in a pull request with the changes: https://github.com/markkimsal/statsd-elasticsearch-backend/pull/20

**Comment by markkimsal** [comment]
Thanks for the updates on 2.0.  I'll merge this asap.

**Comment by fiunchinho** [comment]
Can we close this one?
