### ISSUE TITLE
no automatic reconnect

### ISSUE THREAD

**Issue by imreACTmd** [markkimsal/statsd-elasticsearch-backend#23]
I don't know enough node to fix this, but when my ES server goes away, then comes back up, the backend never establishes a connection again.

**Comment by markkimsal** [comment]
Are there any errors printed to the statsd console?

**Comment by imreACTmd** [comment]
I wasn't running it in the foreground but I will try. stracing the process didn't show any attempts and no log messages either.

**Comment by markkimsal** [comment]
This seems pretty strange.  Every flush is a new HTTP connection.  The on('error') should be triggered for http request connection issues around line 123 in lib/elasticsearch.js

**Comment by markkimsal** [comment]
I think you can configure statsd's logger to log to syslog.  Something like:

{
backends : [ ... ],
elasticsearch: { ... },
logger: {
  level: 'LOG_INFO',
  backend: 'syslog'
},
...
}

**Comment by imreACTmd** [comment]
I will try that and report back.

**Comment by imreACTmd** [comment]
Cannot reproduce it! Closing.

**Comment by imreACTmd** [comment]
This has happened again on two servers while the ES server was down. I think the HTTP request never timed out.
