### ISSUE TITLE
Double up on Output??

### ISSUE THREAD

**Issue by 326TimesBetter** [markkimsal/statsd-elasticsearch-backend#31]
Can you send your metrics to TWO elasticsearch hosts?? I tried duplicating the block in the statsd output but it threw an error. Do you know if there is a way to accomplish this??

**Comment by markkimsal** [comment]
I'm not sure that statsd has the option to duplicate backend configurations.

You can probably use the statsd repeater and send to two separate statsd instances, each with one statsd-elasticsearch-backend configurations.

https://github.com/etsy/statsd/blob/master/backends/repeater.js
