### ISSUE TITLE
Question: is there a way to edit the timestamp format?

### ISSUE THREAD

**Issue by paul42** [markkimsal/statsd-elasticsearch-backend#34]
I am trying out elastic search 5.0 and I'm not certain if it's my configuration (very possible) or not, but when the timestamp comes in as unix epoch, I'm wondering if kibana isn't picking up the @timestamp field - I'd like to ask if there's a way to convert to iso8601 version instead of unix epoc?

**Comment by aleczadikian** [comment]
Yes, same problem here. It's picking it up as a string.

**Comment by markkimsal** [comment]
The ultimate problem is that ES bulk importer used to allow all values to be sent as strings.  Some time ago they changed this parsing behavior and now date mappings don't try to parse strings as unix epoch values.

All numeric values are sent without double quotes now.
