### ISSUE TITLE
typo error at  statsd-elasticsearch-backend/lib/elasticsearch.js

### ISSUE THREAD

**Issue by kazimsarikaya** [markkimsal/statsd-elasticsearch-backend#38]
please fix typo error at line 129:
 innerPayload += renderKV(statKey, listGuageData[key][statKey]);

listGuageData -> listGaugeData

it gives the error: 
ReferenceError: listGuageData is not defined /usr/local/lib/node_modules/statsd-elasticsearch-backend/lib/elasticsearch.js:129

**Comment by markkimsal** [comment]
fixed by #39
