### ISSUE TITLE
TIMESTAMP

### ISSUE THREAD

**Issue by lineldcosta** [markkimsal/statsd-elasticsearch-backend#8]
Is it possible to change the format of @timestamp  ?

**Comment by nilsga** [comment]
I'm also having troubles with the `@timestamp` field in kibana. I do notice that the index template defines three types, `counter`, `timer` and `timer_data`. However, when statsd pushes the data, another type is also created, `timer_data_stats`. And this type gets the mapping dynamically created, and the `@timestamp` field ends up as a string.

**Comment by imreACTmd** [comment]
ES with their new Beats packages prefers "timestamp". https://www.elastic.co/guide/en/beats/packetbeat/current/exported-fields.html
